version: '3'

services:
  client:
    build: ./frontend-ts
    volumes:
      - ./frontend-ts/src:/app/src
    ports:
      - 3000:3000
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080